phoenix_exfile_test_app-master/web/router.ex
defmodule PhoenixExfileTestApp.Router do
  use PhoenixExfileTestApp.Web, :router

  forward "/attachments", Exfile.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PhoenixExfileTestApp do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/post", PostController
  end
end

web/router.ex
defmodule Database.Router do
  use Database.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Database do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    # This implements the data as a resource
    resources "/datas", DataController
    # These implement the uploading
    get "/upload", UploadController, :upload_form
    post "/upload", UploadController, :upload
  end

  # Other scopes may use custom stacks.
  # scope "/api", Database do
  #   pipe_through :api
  # end
end

web/models/data.ex
defmodule Database.Data do
  use Database.Web, :model
  use Rummage.Ecto

  schema "datas" do
    field :code, :string
    field :idcode, :string
    field :inst, :string
    field :time, :string
    field :first, :string
    field :last, :string
    field :email, :string

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:code, :idcode, :inst, :time, :first, :last, :email])
    |> validate_required([:code, :idcode, :inst, :time, :first, :last, :email])
  end
end

web/controllers/data_controller.ex
defmodule Database.DataController do
  use Database.Web, :controller
  # The Rummage dependency needs to be used here in this controller
  use Rummage.Phoenix.Controller
  alias Database.Data
  # This function eventually queries all the data with the rummage data and renders it in the index.html
  def index(conn, params) do
    datas = Repo.all(Data)
    {query, rummage} = Data
      |> Data.rummage(params["rummage"])
    
    datas = query
      |> Repo.all
    render(conn, "index.html", datas: datas, rummage: rummage)
  end

  
end

web/views/data_view.ex
defmodule Database.DataView do
  use Database.Web, :view
  use Rummage.Phoenix.View
end

web/templates/data/form.html.eex
<%= form_for @changeset, @conn, [multipart: true], fn f -> %>
  <div class="form-group">
    <label>Photo</label>
    <%= file_input f, :photo, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/data/index.html.eex
<h2>Listing the database table</h2>
<!-- Here is the search form that can be used to search by the idcode
 The results are shown after pressign the button-->
<%= search_form(@conn, @rummage, [fields: [idcode: %{label: "", search_type: "ilike"},],
                                            button_class: "button"]) %>
<table class="table">
  <thead>
    <tr>
    <!-- Here I implying a sorting function.
         Yes this was not necesarry for the project but I left it in because its neat :) -->
      <th><%= sort_link @conn, @rummage, [field: :idcode] %></th>
      <th>Institute</th>
      <th>Time</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for data <- @datas do %>
    <tr>
      <!--Here we show the data, which is referenced in @datas.-->
      <td><%= data.idcode %></td>
      <td><%= data.inst %></td>
      <td><%= data.time %></td>
      <td><%= data.first %></td>
      <td><%= data.last %></td>
      <td><%= data.email %></td>
    </tr>
<% end %>

  </tbody>
</table>
<!-- This implying the pagination, meaning the data is now splitted into pages. 
     The amount of data that is displayed per page can be changed in the config/config.ex file. -->
<%= pagination_link(@conn, @rummage) %>
<!-- This button sends the user to the Upload site-->
<span><%= button("Go to Upload page", to: "/upload", method: "get", class: "btn") %></span>

web/templates/data/show.html.eex
<h2>Show data</h2>

<ul>

  <li>
    <strong>Code:</strong>
    <%= @data.code %>
  </li>

  <li>
    <strong>Idcode:</strong>
    <%= @data.idcode %>
  </li>

  <li>
    <strong>Inst:</strong>
    <%= @data.inst %>
  </li>

  <li>
    <strong>Time:</strong>
    <%= @data.time %>
  </li>

  <li>
    <strong>First:</strong>
    <%= @data.first %>
  </li>

  <li>
    <strong>Last:</strong>
    <%= @data.last %>
  </li>

  <li>
    <strong>Email:</strong>
    <%= @data.email %>
  </li>

</ul>

<span><%= link "Edit", to: data_path(@conn, :edit, @data) %></span>
<span><%= link "Back", to: data_path(@conn, :index) %></span>